# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "virtio_pci" "virtio_scsi" "xhci_pci" "sd_mod" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fc2137fa-475a-47a0-8026-b1c13fd23c1f";
    fsType = "btrfs";
    options = ["subvol=@" "compress-force=zstd:1"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/fc2137fa-475a-47a0-8026-b1c13fd23c1f";
    fsType = "btrfs";
    options = ["subvol=@home" "compress-force=zstd:1"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/fc2137fa-475a-47a0-8026-b1c13fd23c1f";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress-force=zstd:1"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/fc2137fa-475a-47a0-8026-b1c13fd23c1f";
    fsType = "btrfs";
    options = ["subvol=@log" "compress-force=zstd:1"];
  };

  fileSystems."/var/lib/machines" = {
    device = "/dev/disk/by-uuid/fc2137fa-475a-47a0-8026-b1c13fd23c1f";
    fsType = "btrfs";
    options = ["subvol=@machines" "compress-force=zstd:1"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AF21-2EF4";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  networking.useDHCP = lib.mkDefault true;

  zramSwap = {
    enable = true;
    priority = 100;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  networking.networkmanager.enable = true;

  networking = {
    hostName = "minior";
    resolvconf.enable = true;
    nameservers = ["1.1.1.1"];
    interfaces = {
      enp3s0.ipv4.addresses = [
        {
          address = "45.8.201.77";
          prefixLength = 24;
        }
      ];
    };
    defaultGateway = {
      address = "45.8.201.1";
      interface = "enp3s0";
    };
  };
}
